In [3]:
import numpy as np

In [5]:
arr=np.random.randint(1,99,(5,4))
arr

array([[25, 59, 42, 38],
       [47, 89, 76,  8],
       [36,  2, 84, 50],
       [25,  9, 95, 95],
       [ 4, 59, 20, 25]])

In [9]:
arr[3][3]

95

In [37]:
arr[3:5,1:3]

array([[ 9, 95],
       [59, 20]])

In [40]:
arr[4,1:3]

array([59, 20])